---
title: "writing_functions"
author: "Austin Hsin"
date: "2023-10-26"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
```

## Function

```{r}
set.seed(1)

x_vec = rnorm(25, mean = 5, sd = 3)
(x_vec - mean(x_vec)) / sd(x_vec)

z_scores = function(x) {
  z = (x - mean(x)) / sd(x)
  z
}

z_scores(x_vec)
```

## Conditional Statements

```{r}
z_scores = function(x) {
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Z scores cannot be computed for length 1 vectors")
  }
  z = mean(x) / sd(x)
  z
}

# Mean
mean_and_sd = function(x) {
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  mean_x = mean(x)
  sd_x = sd(x)
  list(mean = mean_x, 
       sd = sd_x)
}

mean_and_sd = function(x) {
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

# Simulated Table
```{r}
sim_data = tibble(
  x = rnorm(30, mean = 2, sd = 3)
)
sim_data |> 
  summarize(
    mu_hat = mean(x),
    sigma_hat = sd(x)
  )

sim_mean_sd = function(n, mu = 2, sigma = 3) {
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma),
  )
  sim_data |> 
    summarize(
      mu_hat = mean(x),
      sigma_hat = sd(x)
    )
}
```
